Shop.Web/ViewModels/ProductViewModels.cs
using Shop.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Shop.Web.ViewModels
{
    public class ProductSearchViewModel
    {
        public int PageNo { get; set; }
        public List<Product> Products { get; set; }
        public string SearchTerm { get; set; }
    }

    public class NewProductViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }

        public List<Category> AvailableCategories { get; set; }
    }

    public class EditProductViewModel
    {
        public int ID { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }

        public List<Category> AvailableCategories { get; set; }
    }

    public class ProductViewModel
    {
        public Product Product { get; set; }
    }
}

Shop.Web/Controllers/ProductController.cs
using Shop.Entities;
using Shop.Services;
using Shop.Web.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace Shop.Web.Controllers
{
    public class ProductController : Controller
    {
        // ProductsService productsService = new ProductsService();
      //  CategoriesService categoryService = new CategoriesService();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductTable(string search, int? pageNo)
        {


            ProductSearchViewModel model = new ProductSearchViewModel();
            model.PageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;


            //if (pageNo.HasValue)
            //{
            //    if (pageNo > 0)
            //    {
            //        model.PageNo = pageNo.Value;
            //    }
            //    else
            //    {
            //        model.PageNo = 1;
            //    }
            //}
            //else
            //{
            //    model.PageNo = 1;
            //}



            model.Products = ProductsService.ClassObject.GetProducts(model.PageNo);
            if (string.IsNullOrEmpty(search) == false)
            {
                model.SearchTerm = search;
                model.Products = model.Products.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            }

            return PartialView(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            NewProductViewModel model = new NewProductViewModel();
            model.AvailableCategories = CategoriesService.Instance.GetAllCategories();
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {

            var newProduct = new Product();
            newProduct.Name = model.Name;
            newProduct.Description = model.Description;
            newProduct.Price = model.Price;
            newProduct.Category = CategoriesService.Instance.GetCategory(model.CategoryID);
            newProduct.ImageURL = model.ImageURL;
            ProductsService.ClassObject.SaveProduct(newProduct);
            return RedirectToAction("ProductTable");
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();
            var product = ProductsService.ClassObject.GetProduct(ID);
            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.ImageURL = product.ImageURL;

            model.AvailableCategories = CategoriesService.Instance.GetAllCategories();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var existingProduct = ProductsService.ClassObject.GetProduct(model.ID);
            existingProduct.Name = model.Name;
            existingProduct.Description = model.Description;
            existingProduct.Price = model.Price;
            existingProduct.Category = CategoriesService.Instance.GetCategory(model.CategoryID);
            existingProduct.ImageURL = model.ImageURL;
            ProductsService.ClassObject.UpdateProduct(existingProduct);
            return RedirectToAction("ProductTable");
        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductsService.ClassObject.DeleteProduct(ID);
            return RedirectToAction("ProductTable");
        }


        [HttpGet]
        public ActionResult Details(int ID)
        {
            ProductViewModel model = new ProductViewModel();

            model.Product = ProductsService.ClassObject.GetProduct(ID);

            return View(model);
        }
    }
}

Shop.Web/Controllers/WidgetController.cs
using Shop.Services;
using Shop.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Web.Controllers
{
    public class WidgetController : Controller
    {
        // GET: Widget
        public ActionResult Products(bool isLatestProducts, int? CategoryID)
        {
            ProductsWidgetViewModels model = new ProductsWidgetViewModels();
            model.isLatestProducts = isLatestProducts;


            if (isLatestProducts)
            {
                model.Products = ProductsService.ClassObject.GetLatestProducts(4);
            }
            else if (CategoryID.HasValue && CategoryID.Value > 0)
            {
                model.Products = ProductsService.ClassObject.GetProductsByCategory(CategoryID.Value, 4);

            }
            else
            {
                model.Products = ProductsService.ClassObject.GetProducts(1, 8);
            }
            return PartialView(model);
        }
    }
}

Shop.Web/Views/Product/Create.cshtml
@model Shop.Web.ViewModels.NewProductViewModel
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/placeholder-image.png";
}
<h2>Створення товару</h2>
<form id="createProduct">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Категорія</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        <option value="@category.ID">@category.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label>Ім'я</label>
                <input class="form-control" name="Name" />
            </div>
            <div class="form-group">
                <label>Опис</label>
                <input class="form-control" name="Description" />
            </div>

            <div class="form-group">
                <label>Ціна</label>
                <input class="form-control" name="Price" />
            </div>

            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />

            </div>
            <button id="saveBtn" type="button" class="btn btn-primary">Зберегти</button>
            <button id="cancelBtn" type="button" class="btn btn-primary">Назад</button>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />

            </div>

        </div>

    </div>
</form>


<script>
    $("#imageUpload").change(function () {
        var element = this;
        var formData = new FormData();

        var totalFile = element.files.length;

        for (var i = 0; i < totalFile; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (response) {
                console.log(response);

                if (response.Success) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#productImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });


    $("#saveBtn").click(function () {
        $.ajax({
            type: 'POST',
            url: '/Product/Create',
            data: $("#createProduct").serialize()

        })
            .done(function (response) {
                $("#tableContainer").html(response);
                $("#actionContainer").html("");
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });

    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");

        $("#tableContainer").html(response);
    });
</script>

Shop.Web/Views/Product/Details.cshtml
@model Shop.Web.ViewModels.ProductViewModel

@if (Model != null && Model.Product != null)
{

    var defaultImageURL = "/Content/images/placeholder-image.png";

    var imageURL = string.IsNullOrEmpty(Model.Product.ImageURL) ? defaultImageURL : Model.Product.ImageURL;

    <div class="page-title parallax parallax1">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-title-heading">
                        <h1 class="title">@Model.Product.Name</h1>
                    </div><!-- /.page-title-heading -->
                </div><!-- /.col-md-12 -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.page-title -->

    <section class="flat-row main-shop shop-detail">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="wrap-flexslider">
                        <div class="inner">
                            <div class="flexslider style-1 has-relative">
                                <ul class="slides">
                                    <li data-thumb="@imageURL">
                                        <img src="@imageURL" alt="Image">
                                        <div class="flat-icon style-1">
                                            <a href="@imageURL" class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                        </div>
                                </ul>
                            </div><!-- /.flexslider -->
                        </div>
                    </div>
                </div><!-- /.col-md-6 -->

                <div class="col-md-6">
                    <div class="product-detail">
                        <div class="inner">
                            <div class="content-detail">
                                <h2 class="product-title">@Model.Product.Name</h2>
                                <p>
                                    @Model.Product.Description
                                </p>
                                <div class="price">
                                    <ins>
                                        <span class="amount">
                                            $ @Model.Product.Price
                                        </span>
                                    </ins>
                                </div>
                                <div class="product-quantity">
                                    <div class="quantity">
                                        <input type="text" value="1" name="quantity-number" class="quantity-number">
                                        <span class="inc quantity-button">+</span>
                                        <span class="dec quantity-button">-</span>
                                    </div>


                                    <div class="add-to-cart">
                                        <a href="#">Додати до кошика</a>
                                    </div>
                                    <div class="box-like">
                                        <span>Категорія: </span><a href="#">@Model.Product.Category.Name</a>
                                    </div>
                                </div>

                                <ul class="flat-socials">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div><!-- /.product-detail -->
                </div>
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section><!-- /.flat-row -->

    <section class="flat-row shop-detail-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="flat-tabs style-1 has-border">
                        <div class="inner">
                            <ul class="menu-tab">

                                <li>Відгуки</li>
                            </ul>
                            <div class="content-tab">
                                <div class="content-inner">
                                    <div class="inner max-width-83 padding-top-33">
                                        <ol class="review-list">
                                            <li class="review">
                                                <div class="thumb">
                                                    <img src="images/avatar-1.png" alt="Image">
                                                </div>
                                                <div class="text-wrap">
                                                    <div class="review-meta">
                                                        <h5 class="name">Sophia Rosla</h5>
                                                        <div class="flat-star style-1">
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star-half-o"></i>
                                                        </div>
                                                    </div>
                                                    <div class="review-text">
                                                        <p>I wanted to thank you so much for the rug we have received it really is beautiful and expertly made. I will be recommending you to all our friends.</p>
                                                    </div>
                                                </div>
                                            </li><!--  /.review    -->
                                            <li class="review">
                                                <div class="thumb">
                                                    <img src="images/avatar.png" alt="Image">
                                                </div>
                                                <div class="text-wrap">
                                                    <div class="review-meta">
                                                        <h5 class="name">Jayne Haughton</h5>
                                                        <div class="flat-star style-1">
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star-half-o"></i>
                                                        </div>
                                                    </div>
                                                    <div class="review-text">
                                                        <p class="line-height-28">Customer service is very important part of the buying experience to us and we must say that we have found Utility's to be impressive - we will certainly look to buy again in future.</p>
                                                    </div>
                                                </div>
                                            </li><!--  /.review    -->
                                        </ol><!-- /.review-list -->
                                        <div class="comment-respond review-respond" id="respond">
                                            <div class="comment-reply-title margin-bottom-14">
                                                <h5>Write a review</h5>
                                                <p>Your email address will not be published. Required fields are marked *</p>
                                            </div>
                                            <form novalidate="" class="comment-form review-form" id="commentform" method="post" action="#">
                                                <p class="flat-star style-2">
                                                    <label>Rating*:</label>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </p>
                                                <p class="comment-form-comment">
                                                    <label>Review*</label>
                                                    <textarea class="" tabindex="4" name="comment" required> </textarea>
                                                </p>
                                                <p class="comment-name">
                                                    <label>Name*</label>
                                                    <input type="text" aria-required="true" size="30" value="" name="name" id="name">
                                                </p>
                                                <p class="comment-email">
                                                    <label>Email*</label>
                                                    <input type="email" size="30" value="" name="email" id="email">
                                                </p>
                                                <p class="comment-form-notify clearfix">
                                                    <input type="checkbox" name="check-notify" id="check-notify"> <label for="check-notify">Notify me of new posts by email</label>
                                                </p>
                                                <p class="form-submit">
                                                    <button class="comment-submit">Submit</button>
                                                </p>
                                            </form>
                                        </div><!-- /.comment-respond -->
                                    </div>
                                </div><!-- /.content-inner -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- /.shop-detail-content -->


    <section class="flat-row shop-related">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title-section margin-bottom-55">
                        <h2 class="title">Супутні товари</h2>
                    </div>
                    @{ Html.RenderAction("Products", "Widget", new { isLatestProducts = false, CategoryID = Model.Product.Category.ID });}
                </div>
            </div><!-- /.row -->
        </div>
    </section>
}

Shop.Web/Views/Product/Edit.cshtml
@model Shop.Web.ViewModels.EditProductViewModel
@{
    ViewBag.Title = "Edit";
    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/placeholder-image.png";
}

<h2>Edit Product</h2>

<form id="editProduct">
    <input type="hidden" name="ID" value="@Model.ID" />
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Категорія</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        var selected = category.ID == Model.CategoryID ? "selected" : string.Empty;
                        <option value="@category.ID" @selected>@category.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label>Ім'я</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label>Опис</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>
            <div class="form-group">
                <label>Ціна</label>
                <input class="form-control" name="Price" value="@Model.Price" />
            </div>
            <button id="updateBtn" type="button" class="btn btn-primary">Зберегти</button>
            <button id="cancelBtn" type="button" class="btn btn-primary">Назад</button>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />

            </div>

        </div>

    </div>
</form>

<script>
    $("#imageUpload").change(function () {
        var element = this;
        var formData = new FormData();

        var totalFile = element.files.length;

        for (var i = 0; i < totalFile; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (response) {
                console.log(response);

                if (response.Success) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#productImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });


    $("#updateBtn").click(function () {
        $.ajax({
            type: 'POST',
            url: '/Product/Edit',
            data: $("#editProduct").serialize()
        })
            .done(function (response) {
                $("#tableContiner").html(response);
                $("#actionContainer").html("");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");

        $("#tableContainer").html(response);
    });
</script>

Shop.Web/Views/Product/Index.cshtml
@model List<Shop.Entities.Product>

@{
    ViewBag.Title = "Товари";
}

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <div class="title">
                        Товари

                    </div>

                </div>
            </div>

        </div>
        <div id="tableContainer">
            @{
                Html.RenderAction("ProductTable");
            }

        </div>
        <div id="actionContainer">

        </div>

    </div>

</section>

Shop.Web/Views/Product/ProductTable.cshtml
  ﻿@model Shop.Web.ViewModels.ProductSearchViewModel
@{
    ViewBag.Title = "ProductTable";

}


<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Пошук</label>
                    <input class="form-control" id="searchTxt" name="Search" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Дії</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">

                            <button class="form-control" type="button" id="searchBtn">Пошук</button>
                        </div>

                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="resetBtn">Скинути</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="form-control" type="button" id="newBtn">Новий</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Назва продукту</td>
                <td>Категорія</td>
                <td>Ціна</td>
                <td class="wrap-td">Дії</td>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null && Model.Products.Count > 0)
            {
                foreach (var product in Model.Products)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>

                            @if (product.Category != null)
                            {
                                <text>@product.Category.Name</text>
                            }
                            else
                            {
                                <text>-</text>
                            }
                        </td>
                        <td>@product.Price</td>
                        <td class="wrap-td">
                            <button class="editBtn" data-id="@product.ID">Редагувати</button>
                            <button class="deleteBtn" data-id="@product.ID">Видалити</button>
                            <button class="addBtn" data-id="@product.ID">Додати в кошик</button>
                        </td>
                    </tr>

                }
            }
            else
            {
                <tr>

                    <td class="text-danger" colspan="4">Товарів не знайдено.</td>

                </tr>
            }
        </tbody>
    </table>

    <div>
        @if (Model.PageNo != 1)
        {
            <button class="pageBtns" data-pageNo="@(Model.PageNo-1)">Назад</button>
        }

        <button class="pageBtns" data-pageNo="@(Model.PageNo+1)">Вперед</button>
    </div>

</div>
<script>

    $(".pageBtns").click(function () {
        $.ajax({
            url: '/Product/ProductTable',
            data: {
                pageNo: $(this).attr("data-pageNo")
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });





    $("#searchBtn").click(function () {
        var searchValue = $("#searchTxt").val();
        $.ajax({
            url: '/Product/ProductTable',
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });



    $("#resetBtn").click(function () {
		var searchValue = '';

		$.ajax({
			url: '@Url.Action("ProductTable", "Product")',
 			data: {
 				search: searchValue
 			}
 		})
         .done(function (response) {
             $("#tableContainer").html(response);
         })
         .fail(function (XMLHttpRequest, textStatus, errorThrown) {
         	alert("FAIL");
         });
 	});


    $("#newBtn").click(function () {
        $.ajax({
            url: '/Product/Create',
        })
            .done(function (response) {
                $("#actionContainer").html(response);
                focusAction();
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });

    $(".editBtn").click(function () {
        $.ajax({
            url: '/Product/Edit',
            data: {
                ID: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                $("#actionContainer").html(response);
                focusAction();
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });

    $(".deleteBtn").click(function () {
        var confirmDelete = confirm("Ви справді хочете видалити даний продукт?");
        if (confirmDelete == true) {
            $.ajax({
                type: 'POST',
                url: '/Product/Delete',
                data: {
                    ID: $(this).attr('data-id')
                }
            })
                .done(function (response) {
                    $("#tableContainer").html(response);
                })
                .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                    alert("FAIL");
                });
        }

    });

    var products = [];
    $(".addBtn").click(function () {
        var productID = $(this).attr('data-id');

        products.push(productID);
        $.cookie("CartProducts", products.join('-'), { path: '/' });

        alert("Товар додано до кошика!");
    });

    function focusAction() {
        $('html, body').animate({
            scrollTop: ("#actionContainer").offset().top - 100
        }, 1000);
    }
</script>