Shop.Web/ViewModels/CategoryViewModels.cs
using Shop.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Shop.Web.ViewModels
{
    public class NewCategoryViewModels
    {
        [Required]
        [MinLength(5), MaxLength(50)]
        public string Name { get; set; }
        [MaxLength(500)]
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }
        public bool isFeatured { get; set; }
    }

    public class CategorySearchViewModel
    {
        public int PageNo { get; set; }
        public List<Category> Categories { get; set; }
        public string SearchTerm { get; set; }
        public Pager Pager { get; set; }
    }
    public class EditCategoryViewModel
    {
        public int ID { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }

        public string ImageURL { get; set; }

        public bool isFeatured { get; set; }
    }
}

Shop.Web/Controllers/CategoryController.cs
using Shop.Entities;
using Shop.Services;
using Shop.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Web.Controllers
{
   // [Authorize(Roles = "Admin"]
    public class CategoryController : Controller
    {
        //CategoriesService categoriesService = new CategoriesService();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CategoryTable(string search, int? pageNo)
        {
            CategorySearchViewModel model = new CategorySearchViewModel();
            model.SearchTerm = search;

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            var totalRecords = CategoriesService.Instance.GetCategoriesCount(search);
            model.Categories = CategoriesService.Instance.GetCategories(search, pageNo.Value);

            if (model.Categories != null)
            {
                model.Pager = new Pager(totalRecords, pageNo, 3);

                return PartialView("CategoryTable", model);
            }
            else
            {
                return HttpNotFound();
            }
        }


        [HttpGet]
        public ActionResult Create()
        {

            NewCategoryViewModels model = new NewCategoryViewModels();

            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Create(NewCategoryViewModels model)
        {
            if (ModelState.IsValid)
            {
                var newCategory = new Category();
                newCategory.Name = model.Name;
                newCategory.Description = model.Description;
                newCategory.ImageURL = model.ImageURL;
                newCategory.isFeatured = model.isFeatured;

                CategoriesService.Instance.SaveCategory(newCategory);
                return RedirectToAction("CategoryTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }

        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditCategoryViewModel model = new EditCategoryViewModel();

            var category = CategoriesService.Instance.GetCategory(ID);
            model.ID = category.ID;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageURL = category.ImageURL;
            model.isFeatured = category.isFeatured;

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel model)
        {
            var existingCategory = CategoriesService.Instance.GetCategory(model.ID);
            existingCategory.Name = model.Name;
            existingCategory.Description = model.Description;
            existingCategory.ImageURL = model.ImageURL;
            existingCategory.isFeatured = model.isFeatured;
            CategoriesService.Instance.UpdateCategory(existingCategory);
            return RedirectToAction("CategoryTable");
        }


        [HttpPost]
        public ActionResult Delete(int ID)
        {

            CategoriesService.Instance.DeleteCategory(ID);
            return RedirectToAction("CategoryTable");
        }


    }
}

Shop.Web/Views/Category/CategoryTable.cshtml
@model Shop.Web.ViewModels.CategorySearchViewModel
@{
    ViewBag.Title = "CategoryTable";
}
<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Пошук</label>
                    <input class="form-control" id="searchTxt" name="Search" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Дії</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">

                            <button class="form-control" type="button" id="searchBtn">Пошук</button>
                        </div>

                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="resetBtn">Скинути</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="form-control" type="button" id="newBtn">Новий</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Назва категорії</td>
                <td>Товари</td>
                <td class="wrap-td">Дії</td>
            </tr>
        </thead>
        <tbody>
            @if (Model.Categories != null && Model.Categories.Count > 0)
            {
                foreach (var category in Model.Categories)
                {
                    <tr>
                        <td>@category.Name</td>
                        <td>
                            @category.Products.Count
                        </td>
                        <td class="wrap-td">
                            <button class="editBtn" data-id="@category.ID">Редагувати</button>
                            <button class="deleteBtn" data-id="@category.ID">Видалити</button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr><td colspan="3" class="text-danger">Категорій не знайдено.</td></tr>
            }
        </tbody>
    </table>

    <div>
        @if (Model.Pager != null)
        {

            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageno="1">First</button>
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage - 1)">Назад</button>
            }

            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <button class="@activeClass pageButtons" data-pageno="@page">@page</button>
            }

            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage + 1)">Вперед</button>
                <button class="pageButtons" data-pageno="@Model.Pager.EndPage">Остання</button>
            }
        }
    </div>

</div>
<script>

    $(".pageButtons").click(function () {
        $.ajax({
            url: '/Category/CategoryTable',
            data: {
                pageNo: $(this).attr("data-pageNo")
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });

    $("#searchBtn").click(function () {
        var searchValue = $("#searchTxt").val();
        $.ajax({
            url: '/Category/CategoryTable',
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });

     $("#resetBtn").click(function () {
		var searchValue = '';

		$.ajax({
			url: '@Url.Action("CategoryTable", "Category")',
 			data: {
 				search: searchValue
 			}
 		})
         .done(function (response) {
             $("#tableContainer").html(response);
         })
         .fail(function (XMLHttpRequest, textStatus, errorThrown) {
         	alert("FAIL");
         });
 	});

    $("#newBtn").click(function () {
        $.ajax({
            url: '/Category/Create',
        })
            .done(function (response) {
                $("#actionContainer").html(response);
                focusAction();
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });

    $(".editBtn").click(function () {
        $.ajax({
            url: '/Category/Edit',
            data: {
                ID: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                $("#actionContainer").html(response);
                focusAction();
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });

    $(".deleteBtn").click(function () {
        var confirmDelete = confirm("Ви справді хочете видалити даний продукт?");
        if (confirmDelete == true) {
            $.ajax({
                type: 'POST',
                url: '/Category/Delete',
                data: {
                    ID: $(this).attr('data-id')
                }
            })
                .done(function (response) {
                    $("#tableContainer").html(response);
                })
                .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                    alert("FAIL");
                });
        }

    });

    function focusAction() {
        $('html, body').animate({
            scrollTop: ("#actionContainer").offset().top - 100
        }, 1000);
    }
</script>

Shop.Web/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";

    var imageURL = "/Content/images/placeholder-image.png";
}
<form id="createCategory">

    <h3>Створити категорію</h3>
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Ім'я</label>
                <input class="form-control" name="Name" />
            </div>

            <div class="form-group">
                <label>Опис</label>
                <input class="form-control" name="Description" />
            </div>

            <div class="form-group">
                <label>Зображення</label>
                <input id="ImageURL" name="ImageURL" type="hidden" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>

            <div class="form-group">

                <label>Запропонувати?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="True" /> Так</label>
                    </div>
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="False" /> Ні</label>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="categoryImage" src="@imageURL" />
            </div>
        </div>
    </div>
    <button id="saveBtn" type="button" class="btn btn-primary">Зберегти</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Назад</button>
</form>

<script>
    $("#imageUpload").change(function () {
        var element = this;
        var formData = new FormData();

        var totalFile = element.files.length;

        for (var i = 0; i < totalFile; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $('#createCategory').validate({
            rules: {
                Name: {
                    required: true,
                    minlength: 5,
                    maxlength: 50,
                },
                Description: {
                    maxlength: 500
                }
            },
            messages: {
                Name: {
                    required: 'Назва є обов*язковим полем',
                    minlength: 'Мінімальна довжина - 5',
                    maxlength: 'Максимальна довжина - 50'
                },
                Description: {
                    maxlength: 'Максимальна довжина - 500'
                }
            }
        });


        $.ajax({
            type: 'POST',
            url: '/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (response) {
                console.log(response);

                if (response.Success) {
                    $("#ImageURL").val(response.ImageURL);
                    $("#categoryImage").attr("src", response.ImageURL);
                }
            })
            .fail(function (XMlHttpRequest, textStatus, errorThrow) {
                alert("FAIL");
            });
    });
    $("#saveBtn").click(function () {
        if ($("#createCategory").valid()) {
            $.ajax({
                type: 'POST',
                url: '/Category/Create',
                data: $("#createCategory").serialize()
            })
                .done(function (response) {
                    $("#tableContainer").html(response);
                    $("#actionContainer").html("");

                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    swal({
                        title: "Помилка",
                        text: "Будь ласка заповніть всі необхідні поля.",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                });
        } else {
            swal({
                title: "JS помилка",
                text: "Будь ласка заповніть всі необхідні поля.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            });
        }
    });

    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");

        $("#tableContainer").html(response);
    });
</script>

Shop.Web/Views/Category/Delete.cshtml
@model Shop.Entities.Category
@{
    ViewBag.Title = "Delete";
}

<h1>Ви дійсно хочете видалити дану категорію?</h1>
<form method="post">
    <h2>Видалення категорії</h2>
    <input type="hidden" name="ID" value="@Model.ID" />
    <button type="submit">Так, видалити</button>
</form>

<a href="/Index">Відмінити</a>

Shop.Web/Views/Category/Edit.cshtml
@model Shop.Web.ViewModels.EditCategoryViewModel
@{
    ViewBag.Title = "Edit";

    var trueChecked = Model.isFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.isFeatured ? "checked" : string.Empty;

    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/placeholder-image.png";
}

<h2>Edit Category</h2>

<form id="editCategory">
    <input type="hidden" name="ID" value="@Model.ID" />

    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Ім'я</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label>Опис</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>
            <div class="form-group">
                <label>Зображення</label>
                <input type="hidden" id="ImageURL" name="ImageURL" value="@Model.ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>
            <div class="form-group">
                <label>Запропонувати?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="True" @trueChecked /> Так</label>
                    </div>
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="False" @falseChecked /> Ні</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img src="@imageURL" class="img-thumbnail img-fluid" id="categoryImage" />
            </div>
        </div>
    </div>




    <button id="updateBtn" type="button" class="btn btn-primary">Зберегти</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Назад</button>
</form>

<script>
	$("#imageUpload").change(function () {
		var element = this;

		var formData = new FormData();

		var totalFiles = element.files.length;

		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}

		$.ajax({
			type: 'POST',
			url: '/Shared/UploadImage',
			dataType: 'json',
			data: formData,
			contentType: false,
			processData: false
		})
        .done(function (response) {
        	console.log(response);

        	if (response.Success) {
        		$("#ImageURL").val(response.ImageURL);
        		$("#categoryImage").attr("src", response.ImageURL);
        	}
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});


	$("#updateBtn").click(function () {
		$.ajax({
			type: 'POST',
			url: '/Category/Edit',
			data: $("#editCategory").serialize()
		})
        .done(function (response) {
        	$("#tableContiner").html(response);
        	$("#actionContainer").html("");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    });
    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");

        $("#tableContainer").html(response);
    });
</script>

Shop.Web/Views/Category/Index.cshtml
@model List<Shop.Entities.Category>

@{
    ViewBag.Title = "Категорії";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <div class="title">
                        Категорії

                    </div>

                </div>
            </div>

        </div>
        <div id="tableContainer">
            @{
                Html.RenderAction("CategoryTable");
            }

        </div>
        <div id="actionContainer">

        </div>

    </div>

</section>