Shop.Web/ViewModels/SharedViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Shop.Web.ViewModels
{

    public class BaseListingViewModel
    {

    }
    public class Pager
    {
        public Pager(int totalItems, int? page, int pageSize = 10)
        {
            if (pageSize == 0) pageSize = 10;

            var totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);//отримуємо скільки всього сторінок
            var currentPage = page != null ? (int)page : 1; //отримуємо поточну сторінку
            var startPage = currentPage - 5; //стартова сторінка
            var endPage = currentPage + 4;//остання сторінка
            if (startPage <= 0)
            {
                endPage -= (startPage - 1);
                startPage = 1;
            }
            if (endPage > totalPages)
            {
                endPage = totalPages;
                if (endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }

            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;
        }

        public int TotalItems { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }
        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set; }
    }
}

Shop.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Shop.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            { 
                var file = Request.Files[0];
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);


                file.SaveAs(path);
                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, ex.Message };
            }

            return result;
        }
    }
}

Shop.Web/Controllers/ShopController.cs
using Shop.Services;
using Shop.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Web.Controllers
{
    [Authorize]
    public class ShopController : Controller

    {
        public ActionResult Index(string searchTerm, int? minPrice, int? maxPrice, int? categoryID, int? sortBy)
        {
            ShopViewModel model = new ShopViewModel();

            model.FeaturedCategories = CategoriesService.Instance.GetFeaturedCategories();
            model.MaximumPrice = ProductsService.ClassObject.GetMaximumPrice();
            model.Products = ProductsService.ClassObject.SearchProducts(searchTerm, minPrice, maxPrice, categoryID, sortBy);
            model.sortBy = sortBy;
            return View(model);
        }



        // GET: Shop

        public ActionResult Checkout()
        {
            CheckoutViewModels model = new CheckoutViewModels();
            var CartProductCookie = Request.Cookies["CartProducts"];

            if (CartProductCookie != null)
            {
                model.CartProductsIds = CartProductCookie.Value.Split('-').Select(x => int.Parse(x)).ToList();
                model.CartProducts = ProductsService.ClassObject.GetProducts(model.CartProductsIds);
                
            }
            return View(model);
        }
    }
}

Shop.Web/Views/Shared/_Layout.cshtml
@{
    ConfigurationService configurationService = new ConfigurationService();
}

<!DOCTYPE html>
<html>
<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <title>@ViewBag.Title - SHOP</title>

    <meta name="author" content="themesflat.com">

    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Bootstrap  -->
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/bootstrap.css">

    <!-- Theme Style -->
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/style.css">
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/responsive.css">

    <!-- Colors -->
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/colors/color1.css" id="colors">

    <!-- Animation Style -->
    <link rel="stylesheet" type="text/css" href="~/Content/stylesheets/animate.css">


    <!-- Favicon and touch icons  -->
    <link href="~/favicon.ico" rel="shortcut icon">

    <!--[if lt IE 9]>
        <script src="~/Content/javascript/html5shiv.js"></script>
        <script src="~/Content/javascript/respond.min.js"></script>
    <![endif]-->
    <script src="~/Content/javascript/jquery.min.js"></script>
    <script src="~/Content/javascript/main.js"></script>
</head>
<body class="header_sticky header-style-1 has-menu-extra">

    <!-- Preloader -->
    <div id="loading-overlay">
        <div class="loader"></div>
    </div>
    <!-- Boxed -->
    <div class="boxed">
        <div id="site-header-wrap">
            <!-- Header -->
            <header id="header" class="header header-container clearfix">
                <div class="container clearfix" id="site-header-inner">
                    <div id="logo" class="logo float-left">
                        <a href="@Url.Action("Index","Home")" title="logo">
                            <img src="~/Content/images/shop.png" alt="image" width="107" height="24" data-retina="~/Content/images/shop.png" data-width="107" data-height="24">
                        </a>
                    </div><!-- /.logo -->
                    <ul class="menu-extra">
                        <li class="box-cart nav-top-cart-wrapper">
                            <a class="icon_cart nav-cart-trigger active" href="@Url.Action("Checkout", "Shop")"><span id="cartProductsCount">0</span></a>
                        </li>
                        <li >
                            @if (User.Identity.IsAuthenticated)
                            {

                                <a class="icon_login" href="#" hidden="@User.Identity.Name">  </a>
                                @Html.ActionLink("Выйти", "Logout", "Account")


                            }
                            else if (!User.Identity.IsAuthenticated)
                            {

                                @Html.ActionLink("Вхід", "Login", "Account")
                                @Html.ActionLink("Реєстрація", "Register", "Account")

                            }
                        </li>

                    </ul><!-- /.menu-extra -->
                    <div class="nav-wrap">
                        <nav id="mainnav" class="mainnav">
                            <ul class="menu">
                                <li>
                                    <a href="@Url.Action("Index", "Home")">ГОЛОВНА</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "Shop")">МАГАЗИН</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Checkout", "Shop")">ЗАМОВЛЕННЯ</a>

                                </li>
                            </ul>
                        </nav><!-- /.mainnav -->
                    </div><!-- /.nav-wrap -->
                </div><!-- /.container-fluid -->
            </header><!-- /header -->
        </div><!-- /#site-header-wrap -->

        @RenderBody()



        <section class="flat-row mail-chimp">
            <div class="container">
                <div class="row">

                    <div class="col-md-8">
                        <div class="subscribe clearfix">

                            <ul class="flat-social">

                                <li><a href="@configurationService.GetConfig("FacebookURL").Value"><i class="fa fa-facebook"></i></a></li>
                            </ul><!-- /.flat-social -->
                            <ul class="flat-contact">

                                <li class="address">@configurationService.GetConfig("CompanyAddress").Value</li>
                                <li class="phone">@configurationService.GetConfig("CompanyPhone").Value</li>
                                <li class="email">@configurationService.GetConfig("CompanyEmail").Value</li>
                            </ul><!-- /.flat-contact -->

                        </div><!-- /.subscribe -->
                    </div>
                </div>
            </div>
        </section><!-- /.mail-chimp -->
        <!-- Footer -->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="widget widget-brand">

                            <div class="logo logo-footer">
                                <a href="index.html"><img src="~/Content/images/logo@2x.png" alt="image" width="107" height="24"></a>
                            </div>
                            <div class="col-md-12">
                                <p class="copyright text-center">Copyright 2020 <a href="#">SHOP</a></p>
                            </div>
                        </div><!-- /.widget -->
                    </div><!-- /.col-md-3 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </footer><!-- /.footer -->

    </div>
    <!-- Javascript -->
    <script src="~/Content/javascript/main2.js"></script>
    <script src="~/Content/javascript/main.js"></script>
    <script src="~/Content/javascript/tether.min.js"></script>
    <script src="~/Content/javascript/bootstrap.min.js"></script>
    <script src="~/Content/javascript/jquery.easing.js"></script>
    <script src="~/Content/javascript/parallax.js"></script>
    <script src="~/Content/javascript/jquery-waypoints.js"></script>
    <script src="~/Content/javascript/jquery-countTo.js"></script>
    <script src="~/Content/javascript/jquery.countdown.js"></script>
    <script src="~/Content/javascript/jquery.flexslider-min.js"></script>
    <script src="~/Content/javascript/images-loaded.js"></script>
    <script src="~/Content/javascript/jquery.isotope.min.js"></script>
    <script src="~/Content/javascript/magnific.popup.min.js"></script>
    <script src="~/Content/javascript/jquery.hoverdir.js"></script>
    <script src="~/Content/javascript/owl.carousel.min.js"></script>
    <script src="~/Content/javascript/equalize.min.js"></script>
    <script src="~/Content/javascript/gmap3.min.js"></script>
    <script src="~/Content/javascript/jquery-ui.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAIEU6OT3xqCksCetQeNLIPps6-AYrhq-s&region=GB"></script>


    <script src="~/Content/javascript/jquery.cookie.js"></script>


    <!-- Revolution Slider -->
    <script src="~/Content/rev-slider/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/Content/rev-slider/js/jquery.themepunch.revolution.min.js"></script>
    <script src="~/Content/javascript/rev-slider.js"></script>
    <!-- Load Extensions only on Local File Systems ! The following part can be removed on Server for On Demand Loading -->
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.actions.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.carousel.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.migration.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.navigation.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.parallax.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script src="~/Content/rev-slider/js/extensions/revolution.extension.video.min.js"></script>
</body>
</html>